import React from "react";

// export const metadata: Metadata = {
//   title: "Single Video Page",
//   description: "Generated by create next app",
// };


export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div>{children}</div>;
}
