import type { Metadata } from "next";
import React from "react";
import {getVideoByIdCached} from "@/services/api/videos/video.service";

// export const metadata: Metadata = {
//   title: "Single Video Page",
//   description: "Generated by create next app",
// };


export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div>{children}</div>;
}
