import type {Metadata} from "next";
import React from "react";

export const metadata: Metadata = {
    title: "Channel Page",
    description: "Generated by create next app",
};

export default function Layout({
                                   children,
                               }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="px-6 sm:px-16 md:px-[32px] lg:px-[48px] xl:px-[64px] pb-2 z-0">
            {children}
        </div>
    );
}
